//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleBoilerTemp.Web.Models.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationaryRequestDetail
    {
        public long Id { get; set; }
        public Nullable<int> RequestId { get; set; }
        public Nullable<short> ParticularId { get; set; }
        public Nullable<short> UnitId { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<decimal> VateRate { get; set; }
        public Nullable<decimal> FinalRate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual SMS_Particulars SMS_Particulars { get; set; }
        public virtual SMS_Units SMS_Units { get; set; }
        public virtual StationaryRequest StationaryRequest { get; set; }
    }
}
