//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleBoilerTemp.Web.Models.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationaryRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StationaryRequest()
        {
            this.RequesterDetails = new HashSet<RequesterDetail>();
            this.StationaryRequestDetails = new HashSet<StationaryRequestDetail>();
        }
    
        public int RequestId { get; set; }
        public long UserId { get; set; }
        public Nullable<int> TenantId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<byte> IsActive { get; set; }
    
        public virtual AbpTenant AbpTenant { get; set; }
        public virtual AbpUser AbpUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequesterDetail> RequesterDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StationaryRequestDetail> StationaryRequestDetails { get; set; }
        public virtual Status Status { get; set; }
    }
}
